//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplySet
    {
        public int ID { get; set; }
        public int IDRieltor { get; set; }
        public int IDClient { get; set; }
        public int IDRealEstate { get; set; }
        public long Prise { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual RealEstateSet RealEstateSet { get; set; }
        public virtual RieltorSet RieltorSet { get; set; }
    }
}
